# Makefile.in generated by automake 1.10.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# vim: set sw=2 ts=8 sts=0 noet:

# Copyright (C) 2004 Oren Ben-Kiki
# Copyright (C) 2006 Joachim Falk <joachim.falk@gmx.de>
#
# This file is part of the BuildSystem distribution of Joachim Falk;
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation;
# either version 2 of the License, or (at your option) any later version.
# 
# The BuildSystem is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this program; If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# Generate automatic documentation using Doxygen. Goals and variables values
# are controlled by the various DX_COND_??? conditionals set by autoconf.
#
# The provided goals are:
# doxygen-doc: Generate all doxygen documentation.
# doxygen-run: Run doxygen, which will generate some of the documentation
#              (HTML, CHM, CHI, MAN, RTF, XML) but will not do the post
#              processing required for the rest of it (PS, PDF, and some MAN).
# doxygen-man: Rename some doxygen generated man pages.
# doxygen-ps: Generate doxygen PostScript documentation.
# doxygen-pdf: Generate doxygen PDF documentation.
#
# Note that by default these are not integrated into the automake goals. If
# doxygen is used to generate man pages, you can achieve this integration by
# setting man3_MANS to the list of man pages generated and then adding the
# dependency:
#
#   $(man3_MANS): doxygen-doc-am
#
# This will cause make to run doxygen and generate all the documentation.
#
# The following variable is intended for use in Makefile.am:
#
# DX_CLEANFILES = everything to clean.
#
# This is usually added to MOSTLYCLEANFILES.


pkgdatadir = $(datadir)/systemc-vpc
pkglibdir = $(libdir)/systemc-vpc
pkgincludedir = $(includedir)/systemc-vpc
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
DIST_COMMON = $(am__configure_deps) \
	$(srcdir)/../BuildSystem/config.guess \
	$(srcdir)/../BuildSystem/config.sub \
	$(srcdir)/../BuildSystem/depcomp \
	$(srcdir)/../BuildSystem/doxygen.am \
	$(srcdir)/../BuildSystem/install-sh \
	$(srcdir)/../BuildSystem/ltmain.sh \
	$(srcdir)/../BuildSystem/missing $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure \
	$(top_srcdir)/pkginclude/systemcvpc/vpc_config.h.in \
	../BuildSystem/config.guess ../BuildSystem/config.sub \
	../BuildSystem/depcomp ../BuildSystem/install-sh \
	../BuildSystem/ltmain.sh ../BuildSystem/missing
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/../BuildSystem/m4/boilerplate.m4 \
	$(top_srcdir)/../BuildSystem/m4/cross.m4 \
	$(top_srcdir)/../BuildSystem/m4/doxygen.m4 \
	$(top_srcdir)/../BuildSystem/m4/enable-debug.m4 \
	$(top_srcdir)/../BuildSystem/m4/jfsugar.m4 \
	$(top_srcdir)/../BuildSystem/m4/libboost.m4 \
	$(top_srcdir)/../BuildSystem/m4/libcosupport.m4 \
	$(top_srcdir)/../BuildSystem/m4/libsystemc.m4 \
	$(top_srcdir)/../BuildSystem/m4/libxercesc.m4 \
	$(top_srcdir)/../BuildSystem/m4/pkgcheck.m4 \
	$(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h \
	$(top_builddir)/pkginclude/systemcvpc/vpc_config.h
CONFIG_CLEAN_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(libdir)"
libLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(lib_LTLIBRARIES)
libsystemcvpc_la_DEPENDENCIES =  \
	$(top_srcdir)/../Support/libcosupport-systemc.la \
	$(top_srcdir)/../Support/libcosupport-tracing.la \
	$(top_srcdir)/../Support/libcosupport-streams.la
am_libsystemcvpc_la_OBJECTS = common.lo Component.lo Mappings.lo \
	Route.lo Scheduler.lo Timing.lo VpcTask.lo VpcApi.lo \
	AVBScheduler.lo FCFSScheduler.lo FlexRayScheduler.lo \
	PriorityScheduler.lo PrioritySchedulerNoPreempt.lo \
	RateMonotonicScheduler.lo RoundRobinScheduler.lo \
	TimeTriggeredCCScheduler.lo TDMAScheduler.lo MostScheduler.lo \
	MostSecondaryScheduler.lo DataBaseTracer.lo Tracing.lo \
	debug_config.lo BlockingTransport.lo ComponentImpl.lo \
	ConfigCheck.lo Director.lo ScheduledTask.lo Attribute.lo \
	Task.lo VPCBuilder.lo ProcessControlBlock.lo FastLink.lo \
	StaticRoute.lo RouteImpl.lo PowerSumming.lo \
	HysteresisLocalGovernor.lo \
	SelectFastestPowerModeGlobalGovernor.lo \
	PluggablePowerGovernor.lo dll-elf.lo ComponentInfo.lo \
	AbstractComponent.lo
libsystemcvpc_la_OBJECTS = $(am_libsystemcvpc_la_OBJECTS)
libsystemcvpc_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libsystemcvpc_la_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I. -I$(top_builddir)/pkginclude/systemcvpc
depcomp = $(SHELL) $(top_srcdir)/../BuildSystem/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libsystemcvpc_la_SOURCES)
DIST_SOURCES = $(libsystemcvpc_la_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /root/scp/BuildSystem/missing --run aclocal-1.10
AMTAR = ${SHELL} /root/scp/BuildSystem/missing --run tar

# FIXME: Decouple SystemC-VPC and SysteMoC by moving SysteMoC
#        dependant code from SystemC-VPC into SysteMoC
#        restore thread based compute interface to SystemC-VPC
AM_CPPFLAGS = \
			\
	$(BOOST_INCLUDE)        \
	 -I$(top_srcdir)/../Support/pkginclude -I$(top_srcdir)/../Support/pkginclude	\
		\
		\
	-Ipkginclude		\
	-I$(srcdir)/pkginclude

AM_LDFLAGS = \
			\
	$(BOOST_LDFLAGS)        \
	 -L$(top_srcdir)/../Support	\
		\
	

AR = ar
AR_FOR_BUILD = ar
AUTOCONF = ${SHELL} /root/scp/BuildSystem/missing --run autoconf
AUTOHEADER = ${SHELL} /root/scp/BuildSystem/missing --run autoheader
AUTOMAKE = ${SHELL} /root/scp/BuildSystem/missing --run automake-1.10
AWK = gawk
BOOST_BASE = 
BOOST_INCLUDE = 
BOOST_INCPATH = 
BOOST_LDFLAGS = 
BOOST_LIB = 
BOOST_LIBMTPOSTFIX = 
BOOST_LIBPATH = 
BOOST_LIBPOSTFIX = 
CC = gcc
CCDEPMODE = depmode=gcc3
CC_FOR_BUILD = gcc
CFLAGS = -Wall -ggdb 
COSUPPORT_BASE = 
COSUPPORT_INCLUDE =  -I$(top_srcdir)/../Support/pkginclude -I$(top_srcdir)/../Support/pkginclude
COSUPPORT_INCPATH = $(top_srcdir)/../Support/pkginclude $(top_srcdir)/../Support/pkginclude
COSUPPORT_LDFLAGS =  -L$(top_srcdir)/../Support
COSUPPORT_LIB = 
COSUPPORT_LIBPATH = $(top_srcdir)/../Support
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -Wall -ggdb 
CXX_FOR_BUILD = g++
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DOXYGEN_PAPER_SIZE = 
DSYMUTIL = 
DX_CONFIG = doxygen.cfg
DX_DOCDIR = doxygen-doc
DX_DOT = 
DX_DOXYGEN = 
DX_DVIPS = 
DX_EGREP = 
DX_ENV =  SRCDIR='$(srcdir)' PROJECT='SystemC-VPC--mainline' DOCDIR='doxygen-doc' VERSION='0.8' HAVE_DOT='NO' GENERATE_MAN='NO' GENERATE_RTF='NO' GENERATE_XML='NO' GENERATE_HTMLHELP='NO' GENERATE_CHI='NO' GENERATE_HTML='NO' GENERATE_LATEX='NO'
DX_FLAG_chi = 0
DX_FLAG_chm = 0
DX_FLAG_doc = 0
DX_FLAG_dot = 0
DX_FLAG_html = 0
DX_FLAG_man = 0
DX_FLAG_pdf = 0
DX_FLAG_ps = 0
DX_FLAG_rtf = 0
DX_FLAG_xml = 0
DX_HHC = 
DX_LATEX = 
DX_MAKEINDEX = 
DX_PDFLATEX = 
DX_PERL = /usr/bin/perl
DX_PROJECT = SystemC-VPC--mainline
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
F77 = gfortran
FFLAGS = -g -O2
GREP = /bin/grep
INSTALL = /bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /root/scp/BuildSystem/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NMEDIT = 
NM_FOR_BUILD = /usr/bin/nm -B
OBJEXT = o
PACKAGE = systemc-vpc
PACKAGE_BUGREPORT = streubuehr@cs.fau.de
PACKAGE_NAME = SystemC-VPC
PACKAGE_STRING = SystemC-VPC 0.8
PACKAGE_TARNAME = systemc-vpc
PACKAGE_VERSION = 0.8
PATH_SEPARATOR = :
RANLIB = ranlib
RANLIB_FOR_BUILD = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
SYSTEMC_BASE = 
SYSTEMC_INCLUDE = 
SYSTEMC_INCPATH = 
SYSTEMC_LDFLAGS = 
SYSTEMC_LIB = 
SYSTEMC_LIBPATH = 
VERSION = 0.8
XERCES_AUXLIBS = 
XERCES_BASE = 
XERCES_INCLUDE = 
XERCES_INCPATH = 
XERCES_LDFLAGS = 
XERCES_LIB = 
XERCES_LIBPATH = 
abs_builddir = /root/scp/SystemC-VPC
abs_srcdir = /root/scp/SystemC-VPC
abs_top_builddir = /root/scp/SystemC-VPC
abs_top_srcdir = /root/scp/SystemC-VPC
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_F77 = gfortran
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
auxdir = $(top_builddir)/../BuildSystem
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = $(SHELL) /root/scp/BuildSystem/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkg_boost_builddir = 
pkg_boost_srcdir = 
pkg_cosupport_builddir = $(top_srcdir)/../Support
pkg_cosupport_srcdir = $(top_srcdir)/../Support
pkg_systemc_builddir = 
pkg_systemc_srcdir = 
pkg_xerces_builddir = 
pkg_xerces_srcdir = 
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
root_builddir := $(shell cd $(top_builddir)/.. && pwd)

# vim: set noet sw=2 ts=8 sts=0:
#
# Copyright (C) Joachim Falk <joachim.falk@gmx.de> $Date: 2003/01/15 16:43:20 $
#
# Makefile.am is part of the jflib distribution of Joachim Falk;
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation;
# either version 2 of the License, or (at your option) any later version.
#
# The jflib distributio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#
# $Log$
root_srcdir := $(shell cd $(top_srcdir)/.. && pwd)
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
#DX_RUN_GOAL = doxygen-run-am 
##DX_CLEAN_HTML = $(DX_DOCDIR)/html
##DX_CLEAN_CHM = $(DX_DOCDIR)/chm
###DX_CLEAN_CHI = $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).chi
##DX_CLEAN_MAN = $(DX_DOCDIR)/man
##DX_CLEAN_RTF = $(DX_DOCDIR)/rtf
##DX_CLEAN_XML = $(DX_DOCDIR)/xml
##DX_CLEAN_PS = $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).ps
##DX_PS_GOAL = doxygen-ps-am
##DX_CLEAN_PDF = $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).pdf
##DX_PDF_GOAL = doxygen-pdf-am
##DX_CLEAN_LATEX = $(DX_DOCDIR)/latex
#DX_CLEANFILES = \
#    $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).tag \
#    -r \
#    $(DX_CLEAN_HTML) \
#    $(DX_CLEAN_CHM) \
#    $(DX_CLEAN_CHI) \
#    $(DX_CLEAN_MAN) \
#    $(DX_CLEAN_RTF) \
#    $(DX_CLEAN_XML) \
#    $(DX_CLEAN_PS) \
#    $(DX_CLEAN_PDF) \
#    $(DX_CLEAN_LATEX)

SUBDIRS = pkginclude

# This is only needed if there is a configure.in in this directory
ACLOCAL_AMFLAGS = -I ../BuildSystem/m4
lib_LTLIBRARIES = libsystemcvpc.la
libsystemcvpc_la_SOURCES = \
	config/common.cpp			\
	config/Component.cpp			\
	config/Mappings.cpp			\
	config/Route.cpp			\
	config/Scheduler.cpp			\
	config/Timing.cpp			\
	config/VpcTask.cpp			\
	config/VpcApi.cpp			\
						\
	scheduler/AVBScheduler.cpp		\
	scheduler/FCFSScheduler.cpp		\
	scheduler/FlexRayScheduler.cpp		\
	scheduler/PriorityScheduler.cpp		\
	scheduler/PrioritySchedulerNoPreempt.cpp	\
	scheduler/RateMonotonicScheduler.cpp	\
	scheduler/RoundRobinScheduler.cpp	\
	scheduler/TimeTriggeredCCScheduler.cpp	\
	scheduler/TDMAScheduler.cpp		\
	scheduler/MostScheduler.cpp   \
	scheduler/MostSecondaryScheduler.cpp   \
						\
	tracing/DataBaseTracer.cpp		\
	tracing/Tracing.cpp			\
						\
	debug_config.cpp			\
	BlockingTransport.cpp			\
	ComponentImpl.cpp			\
	ConfigCheck.cpp				\
	Director.cpp				\
	ScheduledTask.cpp			\
	Attribute.cpp				\
	Task.cpp				\
	VPCBuilder.cpp				\
	ProcessControlBlock.cpp			\
	FastLink.cpp				\
	StaticRoute.cpp				\
	RouteImpl.cpp				\
	PowerSumming.cpp                        \
	HysteresisLocalGovernor.cpp		\
	SelectFastestPowerModeGlobalGovernor.cpp\
	PluggablePowerGovernor.cpp		\
	dynload/dll-elf.cpp			\
	ComponentInfo.cpp			\
	AbstractComponent.cpp

libsystemcvpc_la_LDFLAGS = \
	-version-info 0:0:0 				\
	-no-undefined					\
	-rdynamic

libsystemcvpc_la_LIBADD = \
	$(top_srcdir)/../Support/libcosupport-systemc.la	\
	$(top_srcdir)/../Support/libcosupport-tracing.la	\
	$(top_srcdir)/../Support/libcosupport-streams.la     \
	-lxerces-c					\
	-lsystemc					\
	-lstdc++					\
	-ldl

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/../BuildSystem/doxygen.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign '; \
	      cd $(srcdir) && $(AUTOMAKE) --foreign  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

pkginclude/systemcvpc/vpc_config.h: pkginclude/systemcvpc/stamp-h2
	@if test ! -f $@; then \
	  rm -f pkginclude/systemcvpc/stamp-h2; \
	  $(MAKE) $(AM_MAKEFLAGS) pkginclude/systemcvpc/stamp-h2; \
	else :; fi

pkginclude/systemcvpc/stamp-h2: $(top_srcdir)/pkginclude/systemcvpc/vpc_config.h.in $(top_builddir)/config.status
	@rm -f pkginclude/systemcvpc/stamp-h2
	cd $(top_builddir) && $(SHELL) ./config.status pkginclude/systemcvpc/vpc_config.h

distclean-hdr:
	-rm -f config.h stamp-h1 pkginclude/systemcvpc/vpc_config.h pkginclude/systemcvpc/stamp-h2
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(libdir)/$$f'"; \
	    $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(libLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(libdir)/$$f"; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$p'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$p"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libsystemcvpc.la: $(libsystemcvpc_la_OBJECTS) $(libsystemcvpc_la_DEPENDENCIES) 
	$(libsystemcvpc_la_LINK) -rpath $(libdir) $(libsystemcvpc_la_OBJECTS) $(libsystemcvpc_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/AVBScheduler.Plo
include ./$(DEPDIR)/AbstractComponent.Plo
include ./$(DEPDIR)/Attribute.Plo
include ./$(DEPDIR)/BlockingTransport.Plo
include ./$(DEPDIR)/Component.Plo
include ./$(DEPDIR)/ComponentImpl.Plo
include ./$(DEPDIR)/ComponentInfo.Plo
include ./$(DEPDIR)/ConfigCheck.Plo
include ./$(DEPDIR)/DataBaseTracer.Plo
include ./$(DEPDIR)/Director.Plo
include ./$(DEPDIR)/FCFSScheduler.Plo
include ./$(DEPDIR)/FastLink.Plo
include ./$(DEPDIR)/FlexRayScheduler.Plo
include ./$(DEPDIR)/HysteresisLocalGovernor.Plo
include ./$(DEPDIR)/Mappings.Plo
include ./$(DEPDIR)/MostScheduler.Plo
include ./$(DEPDIR)/MostSecondaryScheduler.Plo
include ./$(DEPDIR)/PluggablePowerGovernor.Plo
include ./$(DEPDIR)/PowerSumming.Plo
include ./$(DEPDIR)/PriorityScheduler.Plo
include ./$(DEPDIR)/PrioritySchedulerNoPreempt.Plo
include ./$(DEPDIR)/ProcessControlBlock.Plo
include ./$(DEPDIR)/RateMonotonicScheduler.Plo
include ./$(DEPDIR)/RoundRobinScheduler.Plo
include ./$(DEPDIR)/Route.Plo
include ./$(DEPDIR)/RouteImpl.Plo
include ./$(DEPDIR)/ScheduledTask.Plo
include ./$(DEPDIR)/Scheduler.Plo
include ./$(DEPDIR)/SelectFastestPowerModeGlobalGovernor.Plo
include ./$(DEPDIR)/StaticRoute.Plo
include ./$(DEPDIR)/TDMAScheduler.Plo
include ./$(DEPDIR)/Task.Plo
include ./$(DEPDIR)/TimeTriggeredCCScheduler.Plo
include ./$(DEPDIR)/Timing.Plo
include ./$(DEPDIR)/Tracing.Plo
include ./$(DEPDIR)/VPCBuilder.Plo
include ./$(DEPDIR)/VpcApi.Plo
include ./$(DEPDIR)/VpcTask.Plo
include ./$(DEPDIR)/common.Plo
include ./$(DEPDIR)/debug_config.Plo
include ./$(DEPDIR)/dll-elf.Plo

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	mv -f $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

common.lo: config/common.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT common.lo -MD -MP -MF $(DEPDIR)/common.Tpo -c -o common.lo `test -f 'config/common.cpp' || echo '$(srcdir)/'`config/common.cpp
	mv -f $(DEPDIR)/common.Tpo $(DEPDIR)/common.Plo
#	source='config/common.cpp' object='common.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o common.lo `test -f 'config/common.cpp' || echo '$(srcdir)/'`config/common.cpp

Component.lo: config/Component.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Component.lo -MD -MP -MF $(DEPDIR)/Component.Tpo -c -o Component.lo `test -f 'config/Component.cpp' || echo '$(srcdir)/'`config/Component.cpp
	mv -f $(DEPDIR)/Component.Tpo $(DEPDIR)/Component.Plo
#	source='config/Component.cpp' object='Component.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Component.lo `test -f 'config/Component.cpp' || echo '$(srcdir)/'`config/Component.cpp

Mappings.lo: config/Mappings.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Mappings.lo -MD -MP -MF $(DEPDIR)/Mappings.Tpo -c -o Mappings.lo `test -f 'config/Mappings.cpp' || echo '$(srcdir)/'`config/Mappings.cpp
	mv -f $(DEPDIR)/Mappings.Tpo $(DEPDIR)/Mappings.Plo
#	source='config/Mappings.cpp' object='Mappings.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Mappings.lo `test -f 'config/Mappings.cpp' || echo '$(srcdir)/'`config/Mappings.cpp

Route.lo: config/Route.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Route.lo -MD -MP -MF $(DEPDIR)/Route.Tpo -c -o Route.lo `test -f 'config/Route.cpp' || echo '$(srcdir)/'`config/Route.cpp
	mv -f $(DEPDIR)/Route.Tpo $(DEPDIR)/Route.Plo
#	source='config/Route.cpp' object='Route.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Route.lo `test -f 'config/Route.cpp' || echo '$(srcdir)/'`config/Route.cpp

Scheduler.lo: config/Scheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Scheduler.lo -MD -MP -MF $(DEPDIR)/Scheduler.Tpo -c -o Scheduler.lo `test -f 'config/Scheduler.cpp' || echo '$(srcdir)/'`config/Scheduler.cpp
	mv -f $(DEPDIR)/Scheduler.Tpo $(DEPDIR)/Scheduler.Plo
#	source='config/Scheduler.cpp' object='Scheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Scheduler.lo `test -f 'config/Scheduler.cpp' || echo '$(srcdir)/'`config/Scheduler.cpp

Timing.lo: config/Timing.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Timing.lo -MD -MP -MF $(DEPDIR)/Timing.Tpo -c -o Timing.lo `test -f 'config/Timing.cpp' || echo '$(srcdir)/'`config/Timing.cpp
	mv -f $(DEPDIR)/Timing.Tpo $(DEPDIR)/Timing.Plo
#	source='config/Timing.cpp' object='Timing.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Timing.lo `test -f 'config/Timing.cpp' || echo '$(srcdir)/'`config/Timing.cpp

VpcTask.lo: config/VpcTask.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT VpcTask.lo -MD -MP -MF $(DEPDIR)/VpcTask.Tpo -c -o VpcTask.lo `test -f 'config/VpcTask.cpp' || echo '$(srcdir)/'`config/VpcTask.cpp
	mv -f $(DEPDIR)/VpcTask.Tpo $(DEPDIR)/VpcTask.Plo
#	source='config/VpcTask.cpp' object='VpcTask.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o VpcTask.lo `test -f 'config/VpcTask.cpp' || echo '$(srcdir)/'`config/VpcTask.cpp

VpcApi.lo: config/VpcApi.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT VpcApi.lo -MD -MP -MF $(DEPDIR)/VpcApi.Tpo -c -o VpcApi.lo `test -f 'config/VpcApi.cpp' || echo '$(srcdir)/'`config/VpcApi.cpp
	mv -f $(DEPDIR)/VpcApi.Tpo $(DEPDIR)/VpcApi.Plo
#	source='config/VpcApi.cpp' object='VpcApi.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o VpcApi.lo `test -f 'config/VpcApi.cpp' || echo '$(srcdir)/'`config/VpcApi.cpp

AVBScheduler.lo: scheduler/AVBScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AVBScheduler.lo -MD -MP -MF $(DEPDIR)/AVBScheduler.Tpo -c -o AVBScheduler.lo `test -f 'scheduler/AVBScheduler.cpp' || echo '$(srcdir)/'`scheduler/AVBScheduler.cpp
	mv -f $(DEPDIR)/AVBScheduler.Tpo $(DEPDIR)/AVBScheduler.Plo
#	source='scheduler/AVBScheduler.cpp' object='AVBScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AVBScheduler.lo `test -f 'scheduler/AVBScheduler.cpp' || echo '$(srcdir)/'`scheduler/AVBScheduler.cpp

FCFSScheduler.lo: scheduler/FCFSScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT FCFSScheduler.lo -MD -MP -MF $(DEPDIR)/FCFSScheduler.Tpo -c -o FCFSScheduler.lo `test -f 'scheduler/FCFSScheduler.cpp' || echo '$(srcdir)/'`scheduler/FCFSScheduler.cpp
	mv -f $(DEPDIR)/FCFSScheduler.Tpo $(DEPDIR)/FCFSScheduler.Plo
#	source='scheduler/FCFSScheduler.cpp' object='FCFSScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FCFSScheduler.lo `test -f 'scheduler/FCFSScheduler.cpp' || echo '$(srcdir)/'`scheduler/FCFSScheduler.cpp

FlexRayScheduler.lo: scheduler/FlexRayScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT FlexRayScheduler.lo -MD -MP -MF $(DEPDIR)/FlexRayScheduler.Tpo -c -o FlexRayScheduler.lo `test -f 'scheduler/FlexRayScheduler.cpp' || echo '$(srcdir)/'`scheduler/FlexRayScheduler.cpp
	mv -f $(DEPDIR)/FlexRayScheduler.Tpo $(DEPDIR)/FlexRayScheduler.Plo
#	source='scheduler/FlexRayScheduler.cpp' object='FlexRayScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o FlexRayScheduler.lo `test -f 'scheduler/FlexRayScheduler.cpp' || echo '$(srcdir)/'`scheduler/FlexRayScheduler.cpp

PriorityScheduler.lo: scheduler/PriorityScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PriorityScheduler.lo -MD -MP -MF $(DEPDIR)/PriorityScheduler.Tpo -c -o PriorityScheduler.lo `test -f 'scheduler/PriorityScheduler.cpp' || echo '$(srcdir)/'`scheduler/PriorityScheduler.cpp
	mv -f $(DEPDIR)/PriorityScheduler.Tpo $(DEPDIR)/PriorityScheduler.Plo
#	source='scheduler/PriorityScheduler.cpp' object='PriorityScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PriorityScheduler.lo `test -f 'scheduler/PriorityScheduler.cpp' || echo '$(srcdir)/'`scheduler/PriorityScheduler.cpp

PrioritySchedulerNoPreempt.lo: scheduler/PrioritySchedulerNoPreempt.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PrioritySchedulerNoPreempt.lo -MD -MP -MF $(DEPDIR)/PrioritySchedulerNoPreempt.Tpo -c -o PrioritySchedulerNoPreempt.lo `test -f 'scheduler/PrioritySchedulerNoPreempt.cpp' || echo '$(srcdir)/'`scheduler/PrioritySchedulerNoPreempt.cpp
	mv -f $(DEPDIR)/PrioritySchedulerNoPreempt.Tpo $(DEPDIR)/PrioritySchedulerNoPreempt.Plo
#	source='scheduler/PrioritySchedulerNoPreempt.cpp' object='PrioritySchedulerNoPreempt.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PrioritySchedulerNoPreempt.lo `test -f 'scheduler/PrioritySchedulerNoPreempt.cpp' || echo '$(srcdir)/'`scheduler/PrioritySchedulerNoPreempt.cpp

RateMonotonicScheduler.lo: scheduler/RateMonotonicScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RateMonotonicScheduler.lo -MD -MP -MF $(DEPDIR)/RateMonotonicScheduler.Tpo -c -o RateMonotonicScheduler.lo `test -f 'scheduler/RateMonotonicScheduler.cpp' || echo '$(srcdir)/'`scheduler/RateMonotonicScheduler.cpp
	mv -f $(DEPDIR)/RateMonotonicScheduler.Tpo $(DEPDIR)/RateMonotonicScheduler.Plo
#	source='scheduler/RateMonotonicScheduler.cpp' object='RateMonotonicScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RateMonotonicScheduler.lo `test -f 'scheduler/RateMonotonicScheduler.cpp' || echo '$(srcdir)/'`scheduler/RateMonotonicScheduler.cpp

RoundRobinScheduler.lo: scheduler/RoundRobinScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RoundRobinScheduler.lo -MD -MP -MF $(DEPDIR)/RoundRobinScheduler.Tpo -c -o RoundRobinScheduler.lo `test -f 'scheduler/RoundRobinScheduler.cpp' || echo '$(srcdir)/'`scheduler/RoundRobinScheduler.cpp
	mv -f $(DEPDIR)/RoundRobinScheduler.Tpo $(DEPDIR)/RoundRobinScheduler.Plo
#	source='scheduler/RoundRobinScheduler.cpp' object='RoundRobinScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RoundRobinScheduler.lo `test -f 'scheduler/RoundRobinScheduler.cpp' || echo '$(srcdir)/'`scheduler/RoundRobinScheduler.cpp

TimeTriggeredCCScheduler.lo: scheduler/TimeTriggeredCCScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TimeTriggeredCCScheduler.lo -MD -MP -MF $(DEPDIR)/TimeTriggeredCCScheduler.Tpo -c -o TimeTriggeredCCScheduler.lo `test -f 'scheduler/TimeTriggeredCCScheduler.cpp' || echo '$(srcdir)/'`scheduler/TimeTriggeredCCScheduler.cpp
	mv -f $(DEPDIR)/TimeTriggeredCCScheduler.Tpo $(DEPDIR)/TimeTriggeredCCScheduler.Plo
#	source='scheduler/TimeTriggeredCCScheduler.cpp' object='TimeTriggeredCCScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TimeTriggeredCCScheduler.lo `test -f 'scheduler/TimeTriggeredCCScheduler.cpp' || echo '$(srcdir)/'`scheduler/TimeTriggeredCCScheduler.cpp

TDMAScheduler.lo: scheduler/TDMAScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TDMAScheduler.lo -MD -MP -MF $(DEPDIR)/TDMAScheduler.Tpo -c -o TDMAScheduler.lo `test -f 'scheduler/TDMAScheduler.cpp' || echo '$(srcdir)/'`scheduler/TDMAScheduler.cpp
	mv -f $(DEPDIR)/TDMAScheduler.Tpo $(DEPDIR)/TDMAScheduler.Plo
#	source='scheduler/TDMAScheduler.cpp' object='TDMAScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TDMAScheduler.lo `test -f 'scheduler/TDMAScheduler.cpp' || echo '$(srcdir)/'`scheduler/TDMAScheduler.cpp

MostScheduler.lo: scheduler/MostScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT MostScheduler.lo -MD -MP -MF $(DEPDIR)/MostScheduler.Tpo -c -o MostScheduler.lo `test -f 'scheduler/MostScheduler.cpp' || echo '$(srcdir)/'`scheduler/MostScheduler.cpp
	mv -f $(DEPDIR)/MostScheduler.Tpo $(DEPDIR)/MostScheduler.Plo
#	source='scheduler/MostScheduler.cpp' object='MostScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MostScheduler.lo `test -f 'scheduler/MostScheduler.cpp' || echo '$(srcdir)/'`scheduler/MostScheduler.cpp

MostSecondaryScheduler.lo: scheduler/MostSecondaryScheduler.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT MostSecondaryScheduler.lo -MD -MP -MF $(DEPDIR)/MostSecondaryScheduler.Tpo -c -o MostSecondaryScheduler.lo `test -f 'scheduler/MostSecondaryScheduler.cpp' || echo '$(srcdir)/'`scheduler/MostSecondaryScheduler.cpp
	mv -f $(DEPDIR)/MostSecondaryScheduler.Tpo $(DEPDIR)/MostSecondaryScheduler.Plo
#	source='scheduler/MostSecondaryScheduler.cpp' object='MostSecondaryScheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o MostSecondaryScheduler.lo `test -f 'scheduler/MostSecondaryScheduler.cpp' || echo '$(srcdir)/'`scheduler/MostSecondaryScheduler.cpp

DataBaseTracer.lo: tracing/DataBaseTracer.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT DataBaseTracer.lo -MD -MP -MF $(DEPDIR)/DataBaseTracer.Tpo -c -o DataBaseTracer.lo `test -f 'tracing/DataBaseTracer.cpp' || echo '$(srcdir)/'`tracing/DataBaseTracer.cpp
	mv -f $(DEPDIR)/DataBaseTracer.Tpo $(DEPDIR)/DataBaseTracer.Plo
#	source='tracing/DataBaseTracer.cpp' object='DataBaseTracer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o DataBaseTracer.lo `test -f 'tracing/DataBaseTracer.cpp' || echo '$(srcdir)/'`tracing/DataBaseTracer.cpp

Tracing.lo: tracing/Tracing.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Tracing.lo -MD -MP -MF $(DEPDIR)/Tracing.Tpo -c -o Tracing.lo `test -f 'tracing/Tracing.cpp' || echo '$(srcdir)/'`tracing/Tracing.cpp
	mv -f $(DEPDIR)/Tracing.Tpo $(DEPDIR)/Tracing.Plo
#	source='tracing/Tracing.cpp' object='Tracing.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Tracing.lo `test -f 'tracing/Tracing.cpp' || echo '$(srcdir)/'`tracing/Tracing.cpp

dll-elf.lo: dynload/dll-elf.cpp
	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT dll-elf.lo -MD -MP -MF $(DEPDIR)/dll-elf.Tpo -c -o dll-elf.lo `test -f 'dynload/dll-elf.cpp' || echo '$(srcdir)/'`dynload/dll-elf.cpp
	mv -f $(DEPDIR)/dll-elf.Tpo $(DEPDIR)/dll-elf.Plo
#	source='dynload/dll-elf.cpp' object='dll-elf.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o dll-elf.lo `test -f 'dynload/dll-elf.cpp' || echo '$(srcdir)/'`dynload/dll-elf.cpp

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonemtpy = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d $(distdir) || mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  unlzma -c $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-exec-am: install-libLTLIBRARIES

install-html: install-html-recursive

install-info: install-info-recursive

install-man:

install-pdf: install-pdf-recursive

install-ps: install-ps-recursive

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-libLTLIBRARIES

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) install-am \
	install-strip

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-generic \
	clean-libLTLIBRARIES clean-libtool ctags ctags-recursive dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-recursive uninstall uninstall-am \
	uninstall-libLTLIBRARIES


include $(auxdir)/jfrules.mk

.PHONY: $(DX_RUN_GOAL) $(DX_PS_GOAL) $(DX_PDF_GOAL)

.INTERMEDIATE: $(DX_RUN_GOAL) $(DX_PS_GOAL) $(DX_PDF_GOAL)

##doxygen-ps-am: $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).ps

##$(DX_DOCDIR)/$(PACKAGE)-$(VERSION).ps: $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).tag
##	cd $(DX_DOCDIR)/latex; \
##	rm -f *.aux *.toc *.idx *.ind *.ilg *.log *.out; \
##	$(DX_LATEX) refman.tex; \
##	$(MAKEINDEX_PATH) refman.idx; \
##	$(DX_LATEX) refman.tex; \
##	countdown=5; \
##	while $(DX_EGREP) 'Rerun (LaTeX|to get cross-references right)' \
##	                  refman.log > /dev/null 2>&1 \
##	   && test $$countdown -gt 0; do \
##	    $(DX_LATEX) refman.tex; \
##	    countdown=`expr $$countdown - 1`; \
##	done; \
##	$(DX_DVIPS) -o ../$(PACKAGE)-$(VERSION).ps refman.dvi

##doxygen-pdf-am: $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).pdf

##$(DX_DOCDIR)/$(PACKAGE)-$(VERSION).pdf: $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).tag
##	cd $(DX_DOCDIR)/latex; \
##	rm -f *.aux *.toc *.idx *.ind *.ilg *.log *.out; \
##	$(DX_PDFLATEX) refman.tex; \
##	$(DX_MAKEINDEX) refman.idx; \
##	$(DX_PDFLATEX) refman.tex; \
##	countdown=5; \
##	while $(DX_EGREP) 'Rerun (LaTeX|to get cross-references right)' \
##	                  refman.log > /dev/null 2>&1 \
##	   && test $$countdown -gt 0; do \
##	    $(DX_PDFLATEX) refman.tex; \
##	    countdown=`expr $$countdown - 1`; \
##	done; \
##	mv refman.pdf ../$(PACKAGE)-$(VERSION).pdf

#doxygen-run-am: $(DX_DOCDIR)/$(PACKAGE)-$(VERSION).tag

#$(DX_DOCDIR)/$(PACKAGE)-$(VERSION).tag: $(DX_CONFIG) $(pkginclude_HEADERS)
#	rm -rf $(DX_DOCDIR)
#	$(DX_ENV) $(DX_DOXYGEN) $(srcdir)/$(DX_CONFIG)

#$(DX_DOCDIR)/$(PACKAGE)-$(VERSION).tag: $(DX_CONFIG) $(pkginclude_HEADERS)
#	$(DX_ENV) $(DX_DOXYGEN) $(srcdir)/$(DX_CONFIG)
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
